---
- hosts: all
  gather_facts: false
  tasks:
     #- name: "Fazendo download do docker"
      # shell: sudo wget https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.1.ce-3.el7.x86_64.rpm

     #- name: "Instalando dependências do docker"
      # shell: sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.42-1.gitad8f0f7.el7.noarch.rpm
     - name: "Instalando o docker"
       #shell: sudo yum install docker-ce-18.06.1.ce-3.el7.x86_64.rpm -y
       shell: sudo yum install docker -y
     - name: Install
       shell: sudo pip install requests
       #shell: sudo service docker start
       #ignore_errors: yes
       become: yes

     - name: "Instalando o docker-py"
       command: sudo pip install docker-py

     - name: "Startando o docker"
       command: sudo systemctl start docker
     
     - name: "Instalando docker-compose"
       shell: sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null

     - name: "Instalando docker-compose"
       shell: sudo chmod +x /usr/local/bin/docker-compose
       
     - name: "Instalando docker-compose"
       shell: sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
   
     - name: "Copiando docker-compose"
       copy: src=../docker/docker-compose.yml dest=/tmp/docker-compose.yml
       
     - name: "Deploy APP"
       shell: sudo docker-compose -f /tmp/docker-compose.yml up -d
     - name: "Instalando portainer"
       shell: sudo docker volume create portainer_data
     - name: "Instalando portainer"
       shell: sudo docker run -d -p 8000:8000 -p 8080:8080 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer

    # - name: "Subindo DB"
     #  docker_container:
      #  name: "mysql-local"
       # image: ambientum/mysql:5.7
       # pull: yes
       # state: started

       # command: sleep infinity
       # volumes:
       #   - ./mysql:/var/lib/mysql
       # ports:
        #  - "3306:3306"
       # env:
        #     MYSQL_ROOT_PASSWORD=root
        #    MYSQL_DATABASE=projeto_docker
        #     MYSQL_USER=docker
        #     MYSQL_PASSWORD=docker

     #- name: "Subindo serviço web"
     #  docker_container:
     #   name: "apache-local"
     #   image: ambientum/php:7.0-apache
     #   pull: yes
     #   state: started
     #   published_ports: 
     #     - 8080:8080
     #   command: sleep infinity
     #   volumes:
     #     - ./www/html:/var/www/app/public
     #   ports:
     #     - "8080:8080"
     #   links:
     #     - "mysql-local"

